services:
  - type: web
    name: youtube-downloader-api
    runtime: node
    buildCommand: npm install && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp && chmod +x yt-dlp
    startCommand: node server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
